### ISSUE TITLE
Add link for "Ok let's go!!!"

### ISSUE THREAD

**Issue by maksimdrachov** [serges147/embedded_scheduler#6]
In the README, "Okay Let's Go" needs to link to the relevant [video](https://www.youtube.com/watch?v=Jo6fKboqfMs).

**Comment by pavel-kirienko** [comment]
Thank you for your first issue report in this repo! We accept contributions via pull requests.

**Comment by maksimdrachov** [comment]
I didn't have push rights :(

![image](https://github.com/user-attachments/assets/d7ccd7ef-50d5-4179-a2b5-bd18ad1b9b55)

(I will make a fork)

**Comment by pavel-kirienko** [comment]
Fixed in #7
